name: 'Chromatic'

# Event for the workflow
on:
    push:
        branches:
            - main
        pull_request:
            branches:
                - '*'

# List of jobs
jobs:
    chromatic-deployment:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                  node-version: 14
                  cache: 'yarn'
            - name: Install dependencies
              run: yarn

            - name: Publish to Chromatic
              uses: chromaui/action@v1
              with:
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
